packages:
  - mobile

catalogMode: prefer

catalog:
  "@t3-oss/env-core": ^0.13.11
  "@tanstack/react-query": ^5.101.1
  "@types/react": ^19.2.17
  axios: ^1.18.1
  expo: ^56.0.12
  expo-dev-client: ^56.0.20
  react: 19.2.3
  react-native: 0.85.3
  tailwindcss: ^4.3.1
  typescript: ~6.0.3
  uniwind: ^1.9.0
  vite-plus: latest
  zod: ^4.4.3
  lucide-react-native: ^1.22.0
  react-native-svg: 15.15.4
  expo-secure-store: ~56.0.4
  expo-auth-session: ~56.0.14
  expo-web-browser: ~56.0.5
  expo-http-server: ^0.1.13

allowBuilds:
  esbuild: true

patchedDependencies:
  uniwind: patches/uniwind.patch
